name: Fetch GitHub Contributions

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # ⬅️ Diperlukan agar bisa push ke repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch contributions
        run: |
          mkdir -p public
          curl -H "Authorization: bearer ${{ secrets.GH_TOKEN }}" \
               -X POST \
               -H "Content-Type: application/json" \
               -d '{
                    "query": "query { user(login: \"prasetyoadis\") { contributionsCollection { contributionCalendar { totalContributions weeks { contributionDays { color contributionCount date } } } } } }"
                  }' \
               https://api.github.com/graphql \
               | jq '.data.user.contributionsCollection.contributionCalendar' \
               > public/contributions.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/contributions.json
          git commit -m "Update contributions" || echo "No changes to commit"
          git push
